---
apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 2
  keeperClusterRef:
    name: {{ .Release.Name }}-keeper
  containerTemplate:
    image:
      repository: {{ .Values.server.image.repository }}
      tag: {{ .Values.server.image.tag | quote }}
    {{- with .Values.resources }}
    resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  settings:
    defaultUserPassword:
      passwordType: password
      secret:
        name: clickhouse-secret
        key: default
    enableDatabaseSync: true
    extraUsersConfig:
      users:
        default:
          grants:
            - "GRANT ALL ON *.* TO default WITH GRANT OPTION"
            - "GRANT ALL ON landing_zone.* TO default WITH GRANT OPTION"
        analyst:
          password_sha256_hex: "7233ba38676a086cf01828f09b5cecf3cc2ef7eab7987819ce227db4ff3c8f8b"
          profile: "default"
          quota: "default"
