---
apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  keeperClusterRef:
    name: {{ .Release.Name }}-keeper
  containerTemplate:
    image:
      repository: {{ .Values.server.image.repository }}
      tag: {{ .Values.server.image.tag | quote }}
    {{- with .Values.resources }}
    resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  settings:
    defaultUserPassword:
      passwordType: password
      secret:
        name: clickhouse-secret
        key: default
    enableDatabaseSync: true
